# lightning.pytorch==1.8.3.post1
trainer:
  max_steps: 10000
  devices: 2
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
model:
  class_path: melody_pretrain.model.MelodyPretrainModel
  init_args:
    embedding_dim:
      bar: 32
      position: 192
      duration: 192
      pitch: 384
      tempo: 32
      family: 32
      metrical: 192
      remi: 512
    model_dim: 768
    feedforward_dim: 3072
    num_layers: 12
    num_heads: 12
    dropout: 0.1
    lr: 1e-4
    betas: [0.9, 0.98]
    epsilon: 1e-6
    weight_decay: 0.1
    warmup_percent: 0.1
data:
  batch_size: 96