# lightning.pytorch==1.8.3.post1
model:
  class_path: melody_pretrain.model.MelodyPretrainModel
  init_args:
    embedding_dim:
      bar: 32
      position: 192
      duration: 192
      pitch: 384
      tempo: 32
    model_dim: 768
    feedforward_dim: 2048
    num_layers: 8
    num_heads: 12
    dropout: 0.1
    lr: 5e-4
    betas: [0.9, 0.98]
    weight_decay: 0.01
    warmup_percent: 0.2