# lightning.pytorch==1.8.3.post1
trainer:
  max_steps: 100000
  devices: 2
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
model:
  class_path: melody_pretrain.model.MelodyPretrainModel
  init_args:
    embedding_dim:
      bar: 16
      position: 128
      duration: 128
      pitch: 256
      tempo: 16
      family: 16
      metrical: 128
      remi: 512
    model_dim: 512
    feedforward_dim: 2048
    num_layers: 4
    num_heads: 8
    dropout: 0.1
    lr: 5e-4
    betas: [0.9, 0.98]
    epsilon: 1e-6
    weight_decay: 0.1
    warmup_percent: 0.1
data:
  batch_size: 128