# lightning.pytorch==1.8.3.post1
model:
  class_path: melody_pretrain.model.MelodyPretrainModel
  init_args:
    embedding_dim:
      bar: 16
      position: 64
      duration: 64
      pitch: 128
      tempo: 16
    model_dim: 256
    feedforward_dim: 1024
    num_layers: 4
    num_heads: 4
    dropout: 0.1
    lr: 5e-4
    betas: [0.9, 0.98]
    weight_decay: 0.01
    warmup_percent: 0.2