# lightning.pytorch==1.8.3.post1
model:
  class_path: melody_pretrain.model.MelodyPretrainModel
  init_args:
    embedding_dim:
      bar: 32
      position: 256
      duration: 256
      pitch: 512
      tempo: 32
    model_dim: 384
    feedforward_dim: 1536
    num_layers: 6
    num_heads: 6
    dropout: 0.1
    lr: 5e-4
    betas: [0.9, 0.98]
    weight_decay: 0.01
    warmup_percent: 0.2