# lightning.pytorch==1.8.3.post1
seed_everything: 42
trainer:
  callbacks: CustomWriter
  logger: false
  enable_checkpointing: false
  devices: "0,"
  accelerator: gpu
  precision: 16
  strategy: ddp
model:
  class_path: MelodyCompletionModel
  init_args:
    dataset_dir: experiment/dataset/wikifonia
    conditional_bar_length: 4
    prediction_bar_length: 32
    temperature: 0.9
    top_k: 10
data:
  dataset_dir: experiment/dataset/wikifonia
  batch_size: 1
  num_workers: 2
  pitch_augumentation: false
  times_to_predict: 5
task:
  class_path: LanguageModelingTask
  init_args:
    seq_len: 512
    padding_only: true