# lightning.pytorch==1.8.3.post1
seed_everything: 42
trainer:
  callbacks: CustomWriter
  logger: false
  enable_checkpointing: false
  devices: "1,"
  accelerator: gpu
  precision: 16-mixed
  strategy: ddp
model:
  class_path: MelodyInfillingModel
  init_args:
    dataset_dir: experiment/dataset/wikifonia
    num_middle_bars: 4
    temperature: 0.9
    top_k: 10
data:
  dataset_dir: experiment/dataset/wikifonia
  batch_size: 1
  num_workers: 4
  load_bar_data: true
  pitch_augumentation: false
  times_to_predict: 5
task:
  class_path: InfillingTask
  init_args:
    kind: fixed_bar
    random_crop: false