# lightning.pytorch==1.8.3.post1
trainer:
  devices: "1,"
model:
  class_path: melody_pretrain.model.MelodyTestingModel
  init_args:
    dataset_dir: experiment/dataset/wikifonia
    max_seq_len: 256
    perplexity_stride: 64
data:
  dataset_dir: experiment/dataset/wikifonia
  batch_size: 32
  pitch_augumentation: false
task:
  class_path: LanguageModelingTask
  init_args:
    seq_len: 1024
    random_crop: false