# lightning.pytorch==1.8.3.post1
trainer:
  devices: 1
model:
  class_path: melody_pretrain.model.MelodyTestingModel
  init_args:
    dataset_dir: experiment/dataset/wikifonia
data:
  dataset_dir: experiment/dataset/wikifonia
  batch_size: 32
  load_bar_data: true
  pitch_augumentation: false
task:
  class_path: InfillingTask
  init_args:
    seq_len: 512
    kind: fixed_bar
    random_crop: false