# ngram-multi-single_80
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_80/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi-single_80/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_80/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi-single_80/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# ngram-multi_80
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_80/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi_80/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_80/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi_80/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# single_80
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_80/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/single_80/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_80/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/single_80/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# bar_80
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_80/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/bar_80/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_80/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/bar_80/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# span_80
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_80/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/span_80/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_80/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/span_80/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# ngram-multi-single-permute_60
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single-permute_60/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi-single-permute_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single-permute_60/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi-single-permute_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# ngram-multi-single_60
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_60/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi-single_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_60/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi-single_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# ngram-multi_60
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_60/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_60/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# single_60
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_60/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/single_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_60/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/single_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# bar_60
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_60/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/bar_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_60/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/bar_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# span_60
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_60/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/span_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_60/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/span_60/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# ngram-multi-single_40
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_40/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi-single_40/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_40/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi-single_40/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# ngram-multi_40
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_40/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi_40/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_40/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi_40/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# single_40
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_40/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/single_40/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_40/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/single_40/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# bar_40
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_40/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/bar_40/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_40/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/bar_40/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# span_40
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_40/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/span_40/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_40/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/span_40/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# ngram-multi-single_20
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_20/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi-single_20/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_20/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi-single_20/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# ngram-multi_20
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_20/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi_20/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_20/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/ngram-multi_20/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# single_20
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_20/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/single_20/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_20/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/single_20/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# bar_20
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_20/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/bar_20/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_20/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/bar_20/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
# span_20
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_20/finetune_clm --load_from_checkpoint experiment/ablation_infilling/model/span_20/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt
python main.py fit --config config/trainer.yaml --config config/model/small.yaml --config config/finetune/infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_20/finetune_infilling --load_from_checkpoint experiment/ablation_infilling/model/span_20/pretrain/lightning_logs/version_0/checkpoints/step=100000.ckpt