# ngram-multi-single_80
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_80/finetune_clm --ckpt_path experiment/ablation_infilling/model/ngram-multi-single_80/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_80/finetune_infilling --ckpt_path experiment/ablation_infilling/model/ngram-multi-single_80/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# ngram-multi_80
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_80/finetune_clm --ckpt_path experiment/ablation_infilling/model/ngram-multi_80/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_80/finetune_infilling --ckpt_path experiment/ablation_infilling/model/ngram-multi_80/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# single_80
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_80/finetune_clm --ckpt_path experiment/ablation_infilling/model/single_80/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_80/finetune_infilling --ckpt_path experiment/ablation_infilling/model/single_80/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# bar_80
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_80/finetune_clm --ckpt_path experiment/ablation_infilling/model/bar_80/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_80/finetune_infilling --ckpt_path experiment/ablation_infilling/model/bar_80/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# span_80
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_80/finetune_clm --ckpt_path experiment/ablation_infilling/model/span_80/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_80/finetune_infilling --ckpt_path experiment/ablation_infilling/model/span_80/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# ngram-multi-single-permute_60
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single-permute_60/finetune_clm --ckpt_path experiment/ablation_infilling/model/ngram-multi-single-permute_60/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single-permute_60/finetune_infilling --ckpt_path experiment/ablation_infilling/model/ngram-multi-single-permute_60/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# ngram-multi-single_60
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_60/finetune_clm --ckpt_path experiment/ablation_infilling/model/ngram-multi-single_60/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_60/finetune_infilling --ckpt_path experiment/ablation_infilling/model/ngram-multi-single_60/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# ngram-multi_60
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_60/finetune_clm --ckpt_path experiment/ablation_infilling/model/ngram-multi_60/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_60/finetune_infilling --ckpt_path experiment/ablation_infilling/model/ngram-multi_60/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# single_60
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_60/finetune_clm --ckpt_path experiment/ablation_infilling/model/single_60/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_60/finetune_infilling --ckpt_path experiment/ablation_infilling/model/single_60/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# bar_60
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_60/finetune_clm --ckpt_path experiment/ablation_infilling/model/bar_60/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_60/finetune_infilling --ckpt_path experiment/ablation_infilling/model/bar_60/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# span_60
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_60/finetune_clm --ckpt_path experiment/ablation_infilling/model/span_60/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_60/finetune_infilling --ckpt_path experiment/ablation_infilling/model/span_60/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# ngram-multi-single_40
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_40/finetune_clm --ckpt_path experiment/ablation_infilling/model/ngram-multi-single_40/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_40/finetune_infilling --ckpt_path experiment/ablation_infilling/model/ngram-multi-single_40/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# ngram-multi_40
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_40/finetune_clm --ckpt_path experiment/ablation_infilling/model/ngram-multi_40/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_40/finetune_infilling --ckpt_path experiment/ablation_infilling/model/ngram-multi_40/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# single_40
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_40/finetune_clm --ckpt_path experiment/ablation_infilling/model/single_40/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_40/finetune_infilling --ckpt_path experiment/ablation_infilling/model/single_40/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# bar_40
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_40/finetune_clm --ckpt_path experiment/ablation_infilling/model/bar_40/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_40/finetune_infilling --ckpt_path experiment/ablation_infilling/model/bar_40/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# span_40
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_40/finetune_clm --ckpt_path experiment/ablation_infilling/model/span_40/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_40/finetune_infilling --ckpt_path experiment/ablation_infilling/model/span_40/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# ngram-multi-single_20
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_20/finetune_clm --ckpt_path experiment/ablation_infilling/model/ngram-multi-single_20/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi-single_20/finetune_infilling --ckpt_path experiment/ablation_infilling/model/ngram-multi-single_20/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# ngram-multi_20
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_20/finetune_clm --ckpt_path experiment/ablation_infilling/model/ngram-multi_20/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/ngram-multi_20/finetune_infilling --ckpt_path experiment/ablation_infilling/model/ngram-multi_20/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# single_20
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_20/finetune_clm --ckpt_path experiment/ablation_infilling/model/single_20/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/single_20/finetune_infilling --ckpt_path experiment/ablation_infilling/model/single_20/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# bar_20
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_20/finetune_clm --ckpt_path experiment/ablation_infilling/model/bar_20/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/bar_20/finetune_infilling --ckpt_path experiment/ablation_infilling/model/bar_20/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt
# span_20
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_clm.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_20/finetune_clm --ckpt_path experiment/ablation_infilling/model/span_20/finetune_clm/lightning_logs/version_0/checkpoints/best.ckpt
python main.py test --config config/trainer.yaml --config config/model/small.yaml --config config/predict/test_infilling.yaml --trainer.default_root_dir experiment/ablation_infilling/model/span_20/finetune_infilling --ckpt_path experiment/ablation_infilling/model/span_20/finetune_infilling/lightning_logs/version_0/checkpoints/best.ckpt