# lightning.pytorch==1.8.3.post1
model:
  dataset_dir: experiment/dataset/pretrain_base
  tasks:
    - GeneralTask
data:
  dataset_dir: experiment/dataset/pretrain_base
  data_collator:
    class_path: DataCollatorForPrefixMaskedLanguageModeling
    init_args:
      seq_len: 512
      random_crop: true
      masking:
        class_path: SingleSpanMasking
        init_args:
          corruption_rate: 0.5