# lightning.pytorch==1.8.3.post1
model:
  dataset_dir: experiment/dataset/pretrain_base
data:
  dataset_dir: experiment/dataset/pretrain_base
task:
  class_path: InfillingTask
  init_args:
    kind: single
    corruption_rate: 0.5