# lightning.pytorch==1.8.3.post1
model:
  dataset_dir: experiment/dataset/pretrain_base
  use_span_positional_encoding: true
data:
  dataset_dir: experiment/dataset/pretrain_base
  load_ngram_data: true
task:
  class_path: InfillingTask
  init_args:
    kind:
      - ngram
      - single
    corruption_rate: 0.5
    permutated_infilling: true