# lightning.pytorch==1.8.3.post1
model:
  dataset_dir: experiment/dataset/pretrain_base
data:
  dataset_dir: experiment/dataset/pretrain_base
  load_ngram_data: true
task:
  class_path: ReplacedTokenDetectionTask
  init_args:
    corruption_rate: 0.5