# lightning.pytorch==1.8.3.post1
model:
  lr: 1e-4
  dataset_dir: experiment/dataset/wikifonia
trainer:
  max_steps: 2000
  accumulate_grad_batches: 8
data:
  batch_size: 48
  dataset_dir: experiment/dataset/wikifonia
  data_collator:
    class_path: DataCollatorForCausalLanguageModeling
    init_args:
      seq_len: 512
      random_crop: true
  pitch_augumentation: True