# lightning.pytorch==1.8.3.post1
model:
  dataset_dir: experiment/dataset/wikifonia
trainer:
  max_steps: 1000
  accumulate_grad_batches: 16
data:
  batch_size: 24
  dataset_dir: experiment/dataset/wikifonia
  data_collator:
    class_path: DataCollatorForCausalLanguageModeling
    init_args:
      seq_len: 512
      random_crop: true