# lightning.pytorch==1.8.3.post1
seed_everything: 42
trainer:
  callbacks: CustomWriter
  logger: false
  enable_checkpointing: false
  devices: 1
  accelerator: gpu
  precision: 16
  strategy: ddp
model:
  class_path: MelodyInfillingModel
  init_args:
    dataset_dir: experiment/dataset/wikifonia
    num_middle_bars: 4
    temperature: 0.9
    top_k: 10
data:
  dataset_dir: experiment/dataset/wikifonia
  batch_size: 1
  num_workers: 4
  data_collator:
    class_path: DataCollatorForInfilling
    init_args:
      masking:
        class_path: FixedBarMasking
        init_args:
          num_past_bars: 6
          num_middle_bars: 4
          num_future_bars: 6
          random_crop: false
  load_bar_data: true