# lightning.pytorch==1.8.3.post1
trainer:
  default_root_dir: experiment/model-lmd/pretrain_single
model:
  dataset_dir: experiment/dataset/lmd
data:
  dataset_dir: experiment/dataset/lmd
  data_collator:
    class_path: DataCollatorForPrefixMaskedLanguageModeling
    init_args:
      seq_len: 512
      random_crop: true
      masking:
        class_path: SingleSpanMasking
        init_args:
          corruption_rate: 0.5
  pitch_augumentation: True