# lightning.pytorch==1.8.3.post1
trainer:
  default_root_dir: experiment/model/pretrain_bar
model:
  dataset_dir: experiment/dataset/pretrain_small
data:
  dataset_dir: experiment/dataset/pretrain_small
  data_collator:
    class_path: DataCollatorForPrefixMaskedLanguageModeling
    init_args:
      seq_len: 512
      random_crop: true
      masking:
        class_path: RandomBarMasking
        init_args:
          corruption_rate: 0.3
  load_bar_data: true