# lightning.pytorch==1.8.3.post1
trainer:
  default_root_dir: experiment/model/pretrain_ngram_multi
model:
  dataset_dir: experiment/dataset/pretrain_small
data:
  dataset_dir: experiment/dataset/pretrain_small
  data_collator:
    class_path: DataCollatorForPrefixMaskedLanguageModeling
    init_args:
      seq_len: 512
      random_crop: true
      masking:
        class_path: MultiTargetInfillingMasking
        init_args:
          probabilities: [0.4, 0.4, 0.2]
          maskings:
            - class_path: RandomNgramMasking
              init_args:
                corruption_rate: 0.3
                extra_data_field_name: pitch_ngrams
            - class_path: RandomNgramMasking
              init_args:
                corruption_rate: 0.3
                extra_data_field_name: rhythm_ngrams
            - class_path: SingleSpanMasking
              init_args:
                corruption_rate: 0.5
  load_ngram_data: true