# lightning.pytorch==1.8.3.post1
trainer:
  default_root_dir: experiment/model-lmd/pretrain_ngram_multi
model:
  dataset_dir: experiment/dataset/lmd
data:
  dataset_dir: experiment/dataset/lmd
  data_collator:
    class_path: DataCollatorForPrefixMaskedLanguageModeling
    init_args:
      seq_len: 512
      random_crop: true
      ngram_field_specific_masking: True
      masking:
        class_path: MultiTargetInfillingMasking
        init_args:
          probabilities: [0.3, 0.3, 0.4]
          maskings:
            - class_path: RandomNgramMasking
              init_args:
                corruption_rate: 0.4
                extra_data_field_name: pitch_ngrams
            - class_path: RandomNgramMasking
              init_args:
                corruption_rate: 0.4
                extra_data_field_name: rhythm_ngrams
            - class_path: SingleSpanMasking
              init_args:
                corruption_rate: 0.6
  load_ngram_data: true
  pitch_augumentation: True