# lightning.pytorch==1.8.3.post1
seed_everything: 42
model:
  class_path: melody_pretrain.model.MelodyTestingModel
  init_args:
    dataset_dir: experiment/dataset/wikifonia
    max_seq_len: 512
    perplexity_stride: 128
data:
  batch_size: 16
  dataset_dir: experiment/dataset/wikifonia
  data_collator:
    class_path: DataCollatorForCausalLanguageModeling