# lightning.pytorch==1.8.3.post1
model:
  dataset_dir: experiment/dataset/wikifonia
data:
  dataset_dir: experiment/dataset/wikifonia
  data_collator:
    class_path: DataCollatorForCausalLanguageModeling
    init_args:
      seq_len: 512
      random_crop: false