# lightning.pytorch==1.8.3.post1
seed_everything: 42
trainer:
  accelerator: gpu
  precision: 16-mixed
  strategy: ddp
  log_every_n_steps: 1
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: ModelCheckpoint
      init_args:
        every_n_train_steps: 5000
        save_weights_only: true
        filename: "{step}"
data:
  num_workers: 8