# lightning.pytorch==1.8.3.post1
seed_everything: 42
trainer:
  max_steps: 10000
  accelerator: gpu
  devices: 2
  precision: 16-mixed
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  log_every_n_steps: 1
  strategy:
    class_path: DDPStrategy
    init_args:
      find_unused_parameters: false
  callbacks:
    - class_path: StochasticWeightAveraging
      init_args:
        swa_lrs: 1e-2
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: ModelCheckpoint
      init_args:
        every_n_train_steps: 1000
        save_weights_only: true
        filename: "{step}"
data:
  batch_size: 128
  num_workers: 8