# lightning.pytorch==1.8.3.post1
model:
  lr: 1e-5
  dataset_dir: experiment/dataset/wikifonia
trainer:
  max_steps: 5000
  accumulate_grad_batches: 1
data:
  batch_size: 8
  dataset_dir: experiment/dataset/wikifonia
task: LanguageModelingTask