# lightning.pytorch==1.8.3.post1
model:
  lr: 5e-5
  dataset_dir: experiment/dataset/wikifonia
trainer:
  max_steps: 1000
  accumulate_grad_batches: 1
data:
  batch_size: 32
  dataset_dir: experiment/dataset/wikifonia
task: LanguageModelingTask