# lightning.pytorch==1.8.3.post1
model:
  lr: 5e-5
  dataset_dir: experiment/dataset/wikifonia
trainer:
  max_steps: 1000
  accumulate_grad_batches: 1
data:
  batch_size: 128
  dataset_dir: experiment/dataset/wikifonia
  pitch_augumentation: true
  data_collator:
    class_path: DataCollatorForCausalLanguageModeling
    init_args:
      seq_len: 512
      random_crop: true