# lightning.pytorch==1.8.3.post1
model:
  lr: 5e-5
  dataset_dir: experiment/dataset/wikifonia
  tasks:
    - GeneralTask
trainer:
  max_steps: 500
  accumulate_grad_batches: 2
data:
  batch_size: 96
  dataset_dir: experiment/dataset/wikifonia
  load_bar_data: true
  data_collator:
    class_path: DataCollatorForPrefixMaskedLanguageModeling
    init_args:
      masking:
        class_path: FixedBarMasking
        init_args:
          num_past_bars: 6
          num_middle_bars: 4
          num_future_bars: 6
          random_crop: true