# lightning.pytorch==1.8.3.post1
trainer:
  max_steps: -1
  max_epochs: 30
  devices: "1,"
  accumulate_grad_batches: 1
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: ModelCheckpoint
      init_args:
        save_top_k: -1
        every_n_epochs: 5
        every_n_train_steps:
        save_weights_only: true
        filename: "{epoch}"
model:
  lr: 1e-5
  dataset_dir: experiment/dataset/wikifonia
data:
  batch_size: 16
  dataset_dir: experiment/dataset/wikifonia
  load_bar_data: true
task:
  class_path: InfillingTask
  init_args:
    seq_len: 512
    kind: fixed_bar