# lightning.pytorch==1.8.3.post1
trainer:
  max_steps: -1
  max_epochs: 50
  devices: 2
  accumulate_grad_batches: 1
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: ModelCheckpoint
      init_args:
        monitor: val_loss
        filename: "best"
        save_weights_only: true
    - class_path: EarlyStopping
      init_args:
        monitor: val_loss
        patience: 5
model:
  lr: 1e-5
  fixed_lr: true
  dataset_dir: experiment/dataset/wikifonia
data:
  batch_size: 8
  dataset_dir: experiment/dataset/wikifonia
  load_bar_data: true
task:
  class_path: InfillingTask
  init_args:
    seq_len: 256
    kind: fixed_bar