# lightning.pytorch==1.8.3.post1
trainer:
  max_steps: 20000
  devices: 2
  accumulate_grad_batches: 1
  val_check_interval: 200
  check_val_every_n_epoch:
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: ModelCheckpoint
      init_args:
        monitor: val_loss
        every_n_train_steps: 200
        save_last: true
        save_weights_only: true
        filename: "best"
model:
  lr: 1e-5
  dataset_dir: experiment/dataset/wikifonia
data:
  batch_size: 16
  dataset_dir: experiment/dataset/wikifonia
  load_bar_data: true
task:
  class_path: InfillingTask
  init_args:
    seq_len: 256
    kind: fixed_bar