data:
  dataset_dir: experiment/dataset/melodynet
  load_ngram_data: true
model:
  dataset_dir: experiment/dataset/melodynet
  use_custom_positional_encoding: true
task:
- class_path: InfillingTask
  init_args:
    corruption_rate: 0.6
    kind: pitch_ngram
    seq_len: 256
    permutated_infilling: true
- class_path: InfillingTask
  init_args:
    corruption_rate: 0.6
    kind: rhythm_ngram
    seq_len: 256
    permutated_infilling: true
- class_path: InfillingTask
  init_args:
    corruption_rate: 0.6
    kind: single
    seq_len: 256
