data:
  dataset_dir: experiment/dataset/melodynet
model:
  dataset_dir: experiment/dataset/melodynet
task:
- class_path: InfillingTask
  init_args:
    corruption_rate: 0.8
    kind: single
    seq_len: 256
